version: "3"
services:
    web:
        build: .
        ports:
            - "5555:5555"
        restart: always
    database:
        image: "mysql:8.0.21"
        # volumes:
            # - "./:/var/lib/mysql"
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=6LmRCQBufqprjUpW
