version: "3"
services:
    web:
        build: .
        ports:
            - "5555:5555"
        restart: always
    database:
        image: "mysql:5.7.31"
        volumes:
            - "./db/database/:/var/lib/mysql"
            - "./db/setup/:/docker-entrypoint-initdb.d"
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=6LmRCQBufqprjUpW
